package br.com.eugeniosolucoes.nfse.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-25T13:21:38.327-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "Nfse", 
                  wsdlLocation = "file:nfse.asmx",
                  targetNamespace = "http://notacarioca.rio.gov.br/") 
public class Nfse extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://notacarioca.rio.gov.br/", "Nfse");
    public final static QName NfseSoap = new QName("http://notacarioca.rio.gov.br/", "NfseSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:nfse.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Nfse.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:nfse.asmx");
        }
        WSDL_LOCATION = url;
    }

    public Nfse(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Nfse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Nfse() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns NfseSoap
     */
    @WebEndpoint(name = "NfseSoap")
    public NfseSoap getNfseSoap() {
        return super.getPort(NfseSoap, NfseSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfseSoap
     */
    @WebEndpoint(name = "NfseSoap")
    public NfseSoap getNfseSoap(WebServiceFeature... features) {
        return super.getPort(NfseSoap, NfseSoap.class, features);
    }

}
