package br.com.eugeniosolucoes.nfse.ws;

/**
 * Please modify this class to meet your needs This class is not complete
 */
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.7 2016-08-25T13:21:38.257-03:00
 * Generated source version: 3.1.7
 *
 */
public final class NfseSoap_NfseSoap_Client {

    private static final QName SERVICE_NAME = new QName( "http://notacarioca.rio.gov.br/", "Nfse" );

    private NfseSoap_NfseSoap_Client() {
    }

    public static void main( String args[] ) throws java.lang.Exception {
        URL wsdlURL = Nfse.WSDL_LOCATION;
        if ( args.length > 0 && args[0] != null && !"".equals( args[0] ) ) {
            File wsdlFile = new File( args[0] );
            try {
                if ( wsdlFile.exists() ) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL( args[0] );
                }
            } catch ( MalformedURLException e ) {
                e.printStackTrace();
            }
        }

        Nfse ss = new Nfse( wsdlURL, SERVICE_NAME );
        NfseSoap port = ss.getNfseSoap();

        {
            System.out.println( "Invoking recepcionarLoteRps..." );
            br.com.eugeniosolucoes.nfse.ws.RecepcionarLoteRpsRequest _recepcionarLoteRps_parameters = null;
            br.com.eugeniosolucoes.nfse.ws.RecepcionarLoteRpsResponse _recepcionarLoteRps__return = port.recepcionarLoteRps( _recepcionarLoteRps_parameters );
            System.out.println( "recepcionarLoteRps.result=" + _recepcionarLoteRps__return.outputXML );

        }
        {
            System.out.println( "Invoking consultarNfse..." );
            br.com.eugeniosolucoes.nfse.ws.ConsultarNfseRequest _consultarNfse_parameters = null;
            br.com.eugeniosolucoes.nfse.ws.ConsultarNfseResponse _consultarNfse__return = port.consultarNfse( _consultarNfse_parameters );
            System.out.println( "consultarNfse.result=" + _consultarNfse__return.outputXML );

        }
        {
            System.out.println( "Invoking cancelarNfse..." );
            br.com.eugeniosolucoes.nfse.ws.CancelarNfseRequest _cancelarNfse_parameters = null;
            br.com.eugeniosolucoes.nfse.ws.CancelarNfseResponse _cancelarNfse__return = port.cancelarNfse( _cancelarNfse_parameters );
            System.out.println( "cancelarNfse.result=" + _cancelarNfse__return.outputXML );

        }
        {
            System.out.println( "Invoking gerarNfse..." );
            br.com.eugeniosolucoes.nfse.ws.GerarNfseRequest _gerarNfse_parameters = null;
            br.com.eugeniosolucoes.nfse.ws.GerarNfseResponse _gerarNfse__return = port.gerarNfse( _gerarNfse_parameters );
            System.out.println( "gerarNfse.result=" + _gerarNfse__return.outputXML );

        }
        {
            System.out.println( "Invoking consultarNfsePorRps..." );
            br.com.eugeniosolucoes.nfse.ws.ConsultarNfsePorRpsRequest _consultarNfsePorRps_parameters = null;
            br.com.eugeniosolucoes.nfse.ws.ConsultarNfsePorRpsResponse _consultarNfsePorRps__return = port.consultarNfsePorRps( _consultarNfsePorRps_parameters );
            System.out.println( "consultarNfsePorRps.result=" + _consultarNfsePorRps__return.outputXML );

        }
        {
            System.out.println( "Invoking consultarSituacaoLoteRps..." );
            br.com.eugeniosolucoes.nfse.ws.ConsultarSituacaoLoteRpsRequest _consultarSituacaoLoteRps_parameters = null;
            br.com.eugeniosolucoes.nfse.ws.ConsultarSituacaoLoteRpsResponse _consultarSituacaoLoteRps__return = port.consultarSituacaoLoteRps( _consultarSituacaoLoteRps_parameters );
            System.out.println( "consultarSituacaoLoteRps.result=" + _consultarSituacaoLoteRps__return.outputXML );

        }
        {
            System.out.println( "Invoking consultarLoteRps..." );
            br.com.eugeniosolucoes.nfse.ws.ConsultarLoteRpsRequest _consultarLoteRps_parameters = null;
            br.com.eugeniosolucoes.nfse.ws.ConsultarLoteRpsResponse _consultarLoteRps__return = port.consultarLoteRps( _consultarLoteRps_parameters );
            System.out.println( "consultarLoteRps.result=" + _consultarLoteRps__return.outputXML );

        }

        System.exit( 0 );
    }

}
