package br.com.eugeniosolucoes.nfse.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-25T13:21:38.314-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://notacarioca.rio.gov.br/", name = "NfseSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NfseSoap {

    @WebResult(name = "RecepcionarLoteRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    @WebMethod(operationName = "RecepcionarLoteRps", action = "http://notacarioca.rio.gov.br/RecepcionarLoteRps")
    public RecepcionarLoteRpsResponse recepcionarLoteRps(
        @WebParam(partName = "parameters", name = "RecepcionarLoteRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/")
        RecepcionarLoteRpsRequest parameters
    );

    @WebResult(name = "ConsultarNfseResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    @WebMethod(operationName = "ConsultarNfse", action = "http://notacarioca.rio.gov.br/ConsultarNfse")
    public ConsultarNfseResponse consultarNfse(
        @WebParam(partName = "parameters", name = "ConsultarNfseRequest", targetNamespace = "http://notacarioca.rio.gov.br/")
        ConsultarNfseRequest parameters
    );

    @WebResult(name = "CancelarNfseResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    @WebMethod(operationName = "CancelarNfse", action = "http://notacarioca.rio.gov.br/CancelarNfse")
    public CancelarNfseResponse cancelarNfse(
        @WebParam(partName = "parameters", name = "CancelarNfseRequest", targetNamespace = "http://notacarioca.rio.gov.br/")
        CancelarNfseRequest parameters
    );

    @WebResult(name = "GerarNfseResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    @WebMethod(operationName = "GerarNfse", action = "http://notacarioca.rio.gov.br/GerarNfse")
    public GerarNfseResponse gerarNfse(
        @WebParam(partName = "parameters", name = "GerarNfseRequest", targetNamespace = "http://notacarioca.rio.gov.br/")
        GerarNfseRequest parameters
    );

    @WebResult(name = "ConsultarNfsePorRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    @WebMethod(operationName = "ConsultarNfsePorRps", action = "http://notacarioca.rio.gov.br/ConsultarNfsePorRps")
    public ConsultarNfsePorRpsResponse consultarNfsePorRps(
        @WebParam(partName = "parameters", name = "ConsultarNfsePorRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/")
        ConsultarNfsePorRpsRequest parameters
    );

    @WebResult(name = "ConsultarSituacaoLoteRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    @WebMethod(operationName = "ConsultarSituacaoLoteRps", action = "http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps")
    public ConsultarSituacaoLoteRpsResponse consultarSituacaoLoteRps(
        @WebParam(partName = "parameters", name = "ConsultarSituacaoLoteRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/")
        ConsultarSituacaoLoteRpsRequest parameters
    );

    @WebResult(name = "ConsultarLoteRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    @WebMethod(operationName = "ConsultarLoteRps", action = "http://notacarioca.rio.gov.br/ConsultarLoteRps")
    public ConsultarLoteRpsResponse consultarLoteRps(
        @WebParam(partName = "parameters", name = "ConsultarLoteRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/")
        ConsultarLoteRpsRequest parameters
    );
}
