//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 08:33:20 PM BRT 
//


package br.com.eugeniosolucoes.nfse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Rps" type="{http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd}tcRps"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rps"
})
@XmlRootElement(name = "GerarNfseEnvio", namespace = "http://notacarioca.rio.gov.br/WSNacional/XSD/1/nfse_pcrj_v01.xsd")
public class GerarNfseEnvio {

    @XmlElement(name = "Rps", namespace = "http://notacarioca.rio.gov.br/WSNacional/XSD/1/nfse_pcrj_v01.xsd", required = true)
    protected TcRps rps;

    /**
     * Gets the value of the rps property.
     * 
     * @return
     *     possible object is
     *     {@link TcRps }
     *     
     */
    public TcRps getRps() {
        return rps;
    }

    /**
     * Sets the value of the rps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcRps }
     *     
     */
    public void setRps(TcRps value) {
        this.rps = value;
    }

}
