//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 08:33:20 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.eugeniosolucoes.nfse.model;
