//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 08:33:20 PM BRT 
//


package br.com.eugeniosolucoes.nfse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcDadosServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcDadosServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Valores" type="{http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd}tcValores"/>
 *         &lt;element name="ItemListaServico" type="{http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd}tsItemListaServico"/>
 *         &lt;element name="CodigoCnae" type="{http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd}tsCodigoCnae" minOccurs="0"/>
 *         &lt;element name="CodigoTributacaoMunicipio" type="{http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd}tsCodigoTributacao"/>
 *         &lt;element name="Discriminacao" type="{http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd}tsDiscriminacao"/>
 *         &lt;element name="CodigoMunicipio" type="{http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd}tsCodigoMunicipioIbge"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDadosServico", propOrder = {
    "valores",
    "itemListaServico",
    "codigoCnae",
    "codigoTributacaoMunicipio",
    "discriminacao",
    "codigoMunicipio"
})
public class TcDadosServico {

    @XmlElement(name = "Valores", required = true)
    protected TcValores valores;
    @XmlElement(name = "ItemListaServico", required = true)
    protected String itemListaServico;
    @XmlElement(name = "CodigoCnae")
    protected Integer codigoCnae;
    @XmlElement(name = "CodigoTributacaoMunicipio", required = true)
    protected String codigoTributacaoMunicipio;
    @XmlElement(name = "Discriminacao", required = true)
    protected String discriminacao;
    @XmlElement(name = "CodigoMunicipio")
    protected int codigoMunicipio;

    /**
     * Gets the value of the valores property.
     * 
     * @return
     *     possible object is
     *     {@link TcValores }
     *     
     */
    public TcValores getValores() {
        return valores;
    }

    /**
     * Sets the value of the valores property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcValores }
     *     
     */
    public void setValores(TcValores value) {
        this.valores = value;
    }

    /**
     * Gets the value of the itemListaServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemListaServico() {
        return itemListaServico;
    }

    /**
     * Sets the value of the itemListaServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemListaServico(String value) {
        this.itemListaServico = value;
    }

    /**
     * Gets the value of the codigoCnae property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodigoCnae() {
        return codigoCnae;
    }

    /**
     * Sets the value of the codigoCnae property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodigoCnae(Integer value) {
        this.codigoCnae = value;
    }

    /**
     * Gets the value of the codigoTributacaoMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTributacaoMunicipio() {
        return codigoTributacaoMunicipio;
    }

    /**
     * Sets the value of the codigoTributacaoMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTributacaoMunicipio(String value) {
        this.codigoTributacaoMunicipio = value;
    }

    /**
     * Gets the value of the discriminacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscriminacao() {
        return discriminacao;
    }

    /**
     * Sets the value of the discriminacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscriminacao(String value) {
        this.discriminacao = value;
    }

    /**
     * Gets the value of the codigoMunicipio property.
     * 
     */
    public int getCodigoMunicipio() {
        return codigoMunicipio;
    }

    /**
     * Sets the value of the codigoMunicipio property.
     * 
     */
    public void setCodigoMunicipio(int value) {
        this.codigoMunicipio = value;
    }

}
